# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  
  config.vm.define "box01" do |b1|
    b1.vm.box = "ubuntu/trusty64"
    b1.vm.hostname = "box01"
    b1.vm.network :private_network, ip: "192.168.56.102"
    b1.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "box01"]
    end
    b1.ssh.insert_key = false
    b1.vm.provision "ansible" do |a|
      a.verbose = "v"
      a.playbook = "../ansible/blank.yml"
    end
  end

  config.vm.define "box02" do |b2|
    b2.vm.box = "ubuntu/trusty64"
    b2.vm.hostname = "box02"
    b2.vm.network :private_network, ip: "192.168.56.103"
    b2.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "box02"]
    end
    b2.ssh.insert_key = false
    b2.vm.provision "ansible" do |a|
      a.verbose = "v"
      a.playbook = "../ansible/blank.yml"
    end
  end


    config.vm.define "box03" do |b3|
    b3.vm.box = "ubuntu/trusty64"
    b3.vm.hostname = "box03"
    b3.vm.network :private_network, ip: "192.168.56.104"
    b3.vm.provider :virtualbox do |v|
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", 512]
      v.customize ["modifyvm", :id, "--name", "box03"]
    end
    b3.ssh.insert_key = false
    b3.vm.provision "ansible" do |a|
      a.verbose = "v"
      a.playbook = "../ansible/blank.yml"
    end
  end
# Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
end
